name: Main workflow

on:
  workflow_dispatch: {}
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  schedule:
    - cron: "0 0 * * 5"

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: flux --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
